name: Deploy to GCS using Terraform
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.6

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/671902319686/locations/global/workloadIdentityPools/github-actions-pool-new/providers/github-actions-provider"
        service_account: "github-actions-sa@itsme-1234.iam.gserviceaccount.com"

    - name: Configure gcloud CLI
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set auth/impersonate_service_account github-actions-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve
